### ISSUE TITLE
Up-to-date documentation for 1.4

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#411]
This is a tracking issue for documentation for 1.4 release. Documentation that needs to be updated and checked include:
* The wiki
* The VPL tutorial
* Offline documentation

**Comment by cbarraud** [comment]
# Wiki

Both EN and FR, other languages on request on mailing list, after check by Christophe.

In details:
* en:visualprogramming
 * image of a book for tutorial - Maria
 * screenshot reference card - Stéph
 * put method B into folding section - Stéph
 * replace video - Christophe
* en:thymiovpl
 * check for when + sound block - Stéph
* en:wininstall - Stéph
 * add note about other windows versions
* en:linuxinstall - Stéph
 * check and update
* en:macinstall - Fanny
 * check and update

# VPL tutorial

* Translate latest changes into French - Luca Mondada

**Comment by cbarraud** [comment]
Hi,

I replace the video in en:visualprogramming. I cut Francesco's video in four parts (on Youtube since this morning). I still have to place the subtitles for these videos.

I also placed the video on top of the page and added the button towards interface on top (below the tutos). We'll have to see if it's good. I also place the Method B and "Thymio is not connected" in collapsible.

I found a few bad links on the bottom of en:visualprogramming. They all point towards the complete tuto and not towards the parts as announced. This should be fixed.

I re-did the same page in the different languages to make them more uniform. There is still some translation to do (italien, spanish: part concerning starting VPL).

The reference card has been done in english, can we translate it ? Is it good ?

**Comment by motib** [comment]
Hi Christophe,

I found a few bad links on the bottom of en:visualprogramming. They all
> point towards the complete tuto and not towards the parts as announced.
> This should be fixed.
>
> Originally, there were separate documents, so there were separate links.
At some point I decided to integrate these into a single (long ...)
document. Someone graciously changed the links so that they all point to
the full tutorial. I don't know if it is even possible to point a link to
within a pdf document. Until the tutorial is restructured as you wrote me,
I suggest removing the links and just leaving the indications that XXX is
in Chapter YYY of the full tutorial.

> The reference card has been done in english, can we translate it ? Is it
> good ?
>

1. There are two reference "cards": one is 2 ordinary A4 pages and the
other is designed for a 6-column 2-sided folded paper or cardboard. The
original LaTeX manual included one of these and I liked it, so I prepared
one for VPL.
2. Of course you can translate one or both of them. The source and images
are in the github for the tutorial.
3. We have a saying: "A baker shouldn't be asked to evaluate his own dough"
:-).

Moti

**Comment by stephanemagnenat** [comment]
Released announced on mailing lists and twitter.

Visual summary of changes from an end-user perspective still required.
