### ISSUE TITLE
Thymio upgrader does not support unpluging and repluging wireless Thymio without restarting

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba#477]
the new upgrader do not work if you update a wireless Thymio, unplug it and plug a new one for massive updating. 
You have to close and reopen. 
This is totally normal because the nodeID is not constant.
If we can improve it could be nice but it is not mandatory

**Comment by stephanemagnenat** [comment]
That is true, because currently Thymio Upgrader does not keep a connection open, as flashing is done in a separate thread for safety. A solution would be to recheck the nodeId just before flashing, within the flashing thread. I can see on Monday whether doing so can be done quickly. Currently I do not have a wireless Thymio with me.

**Comment by stephanemagnenat** [comment]
Should be fixed by commit 9fb9f4e, please test and close if it works correctly.

**Comment by stephanemagnenat** [comment]
Seems to work, closing
