### ISSUE TITLE
Aesl file created in Thymio Blockly standalone cannot be used in Studio

### ISSUE THREAD

**Issue by ypiguet-epfl** [aseba-community/aseba#804]
If you create a program in Thymio Blockly, you save it as a .aesl file and you try to open it in Aseba Studio connected to the same Thymio node, Studio displays _1 scripts have no corresponding nodes in the current network and have not been loaded_ (sic). The source code is displayed in a new tab named _thymio-II (not available)_ without the node-specific controls on the left of the window. Tested in 1.6, macOS 10.12, Thymio simulated in Playground. See also #670.
Suggestion 1: if you can't match the node id, have a button to match the node by name if it's possible ("thymio-II" here).
Suggestion 2: check the grammar in error messages.

**Comment by stephanemagnenat** [comment]
@cor3ntin could you please try to reproduce this?

**Comment by cor3ntin** [comment]
No reproduction on linux, I'll investigate later.

**Comment by mbonani** [comment]
The problem is that when you open a aesl that contain blockly information it crash studio because it want to open blockly that was remove. It works on Linux because Blockly is still there. 
Generate files have also strange info not needed. <xml xmlns="http://www.w3.org/1999/xhtml">
[untitled (8).zip](https://github.com/aseba-community/aseba/files/1799867/untitled.8.zip)

**Comment by cor3ntin** [comment]
I fixed the crash the file opens now fine in Aseba.
However when the file is saved, the parts specific to the missing plugin are lost.
I guess fixing the crash is a reasonable approach for 1.6
